name: Run tests
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  test:
    name: PHP ${{ matrix.php }}, ${{ matrix.dependency-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: ['7.3', '7.4', '8.0', '8.1']
        dependency-version: [prefer-lowest, prefer-stable]
        # [['symfony/console', 'symfony/process'], ...]
        symfony: [['^4.4.30', '^4.4'], ['^5.3.7', '^5.0'], ['^6.0', '^6.0']]
        exclude:
          - php: '7.3'
            symfony: ['^6.0', '^6.0']
          - php: '7.4'
            symfony: ['^6.0', '^6.0']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ matrix.dependency-version }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ matrix.dependency-version }}-
            ${{ runner.os }}-php-${{ matrix.php }}-composer-
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: |
          composer require symfony/console:${{ matrix.symfony[0] }} symfony/process:${{ matrix.symfony[1] }} --no-update --no-interaction
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
          composer require illuminate/view --with-all-dependencies --no-interaction
      - run: vendor/bin/phpunit
