name: Run tests
on:
  push:
    branches: [main, ci]
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  test:
    name: PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony[0] }} ${{ matrix.dependencies }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        php: ['7.3', '7.4', '8.0', '8.1']
        symfony: [[4, '^4.4.30', '^4.4.20'], [5, '^5.3.7', '^5.0.9'], [6, '^6.0', '^6.0']]
        dependencies: [lowest, stable]
        exclude:
          - php: '7.3'
            symfony: ['^6.0', '^6.0']
          - php: '7.4'
            symfony: ['^6.0', '^6.0']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ matrix.dependencies }}-
            ${{ runner.os }}-php-${{ matrix.php }}-composer-
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: |
          composer require symfony/console:${{ matrix.symfony[1] }} symfony/process:${{ matrix.symfony[2] }} --no-update --no-interaction
          composer update --prefer-${{ matrix.dependencies }} --prefer-dist --no-interaction
          composer require illuminate/view:* --with-all-dependencies --no-interaction
      - run: vendor/bin/phpunit
