name: Run Duster

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  duster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "duster"
        uses: tighten/duster-action@v1
        with:
          args: lint
